//! Full-field DEC homogenisation (β).
//!
//! Solves the cell problem $\nabla \cdot (C(x)(\nabla \chi_i + e_i)) = 0$ on a
//! periodic adaptive mesh generated by `cartan-remesh`, using `cartan-dec`'s
//! Hodge-Laplace operators. Returns an effective tensor by volume averaging
//! $\langle C(x)(e_i + \nabla \chi_i) \rangle$.
//!
//! ## Status
//!
//! v1 ships the module scaffolding, the public `FullField<O>` entry point,
//! and `ReliabilityIndicator` that compares mean-field and full-field via
//! affine-invariant distance. The heavy pieces (periodic-cube mesh builder,
//! cell-problem assembly, AMG-CG solver) return `HomogError::Solver(...)`
//! with a clear note pointing at v1.1.

use crate::{error::HomogError, rve::Rve, schemes::Effective, tensor::TensorOrder};

pub mod voxelize;
pub mod mesh;
pub mod cell_problem;
pub mod solver;

pub use mesh::{PeriodicCubeMeshBuilder, PeriodicCubeMeshBuilderOpts};

/// Full-field solver config.
#[derive(Clone, Debug)]
pub struct FullField<O: TensorOrder> {
    pub mesh_opts: PeriodicCubeMeshBuilderOpts,
    pub tol: f64,
    pub max_iter: usize,
    _marker: core::marker::PhantomData<O>,
}

impl<O: TensorOrder> Default for FullField<O> {
    fn default() -> Self {
        Self {
            mesh_opts: PeriodicCubeMeshBuilderOpts::default(),
            tol: 1e-8,
            max_iter: 10_000,
            _marker: core::marker::PhantomData,
        }
    }
}

impl<O: TensorOrder> FullField<O> {
    pub fn new_with_resolution(resolution: usize) -> Self {
        Self {
            mesh_opts: PeriodicCubeMeshBuilderOpts { resolution, refine_depth: 3 },
            ..Default::default()
        }
    }

    /// Compute the effective tensor via the cell-problem solve.
    pub fn homogenize(&self, _rve: &Rve<O>) -> Result<Effective<O>, HomogError> {
        Err(HomogError::Solver(alloc::string::String::from(
            "FullField::homogenize: cell-problem assembly deferred to v1.1. \
             The module scaffold, PeriodicCubeMeshBuilder stub, and reliability \
             indicator are in place. Next: wire cartan-dec::Operators into \
             cell_problem::assemble and solver::solve_cg.")))
    }
}

/// Affine-invariant reliability indicator: d_AI(C_MF, C_FF) on SPD(KM_DIM).
pub fn reliability_indicator_order2(
    c_mf: &nalgebra::Matrix3<f64>, c_ff: &nalgebra::Matrix3<f64>,
) -> Option<f64> {
    use cartan_core::Manifold;
    let spd = cartan_manifolds::Spd::<3>;
    let sa = (c_mf + c_mf.transpose()) * 0.5;
    let sb = (c_ff + c_ff.transpose()) * 0.5;
    spd.dist(&sa, &sb).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn reliability_zero_for_equal_tensors() {
        let c = nalgebra::Matrix3::<f64>::identity() * 3.0;
        let d = reliability_indicator_order2(&c, &c).unwrap();
        assert_relative_eq!(d, 0.0, epsilon = 1e-12);
    }

    #[test]
    fn reliability_monotone_in_eigenvalue_ratio() {
        let a = nalgebra::Matrix3::<f64>::identity() * 1.0;
        let b1 = nalgebra::Matrix3::<f64>::identity() * 2.0;
        let b2 = nalgebra::Matrix3::<f64>::identity() * 10.0;
        let d1 = reliability_indicator_order2(&a, &b1).unwrap();
        let d2 = reliability_indicator_order2(&a, &b2).unwrap();
        assert!(d2 > d1);
    }
}
