//! Symmetry groups as compile-time types.
//!
//! `Fiber` fixes `Element` and `FIBER_DIM` at compile time, so the amplitude
//! count has to be a type-level quantity. Each symmetry is therefore a unit
//! struct implementing [`SymmetryGroup`], in the same shape as `U1Spin2` and
//! `NematicFiber3D` implement `Fiber`.
//!
//! The types name the lift `H^` inside `SU(2)` directly, not the point group
//! `H` inside `SO(3)`. The projection is two-to-one exactly when `-1` lies in
//! `H^`, so a caller wanting the lift of `C_k` asks for `Cyclic<{2 * k}>`.

use cartan_core::rotor::Rotor3;

/// Runtime tag for a symmetry, for serialisation and error messages.
///
/// Dispatch is static through [`SymmetryGroup`]; this is the value-level
/// counterpart.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PointGroupKind {
    /// Cyclic of order `n` inside `SU(2)`.
    Cyclic(usize),
    /// Dicyclic (binary dihedral) of order `4k`.
    Dicyclic(usize),
    /// Binary tetrahedral, order 24.
    BinaryTetrahedral,
    /// Binary octahedral, order 48.
    BinaryOctahedral,
    /// Binary icosahedral, order 120.
    BinaryIcosahedral,
    /// Continuous polar axis, `C_inf_v`; order-parameter manifold `S^2`.
    AxialPolar,
    /// Continuous apolar axis, `D_inf_h`; order-parameter manifold `RP^2`.
    AxialApolar,
}

/// A molecular symmetry, as the subgroup `H^` of `SU(2)` that stabilises the
/// order parameter.
///
/// Not object safe: `elements` returns `impl Iterator`, and dispatch here is
/// static by design. Use [`PointGroupKind`] where a runtime value is wanted.
pub trait SymmetryGroup: Clone + Copy + Send + Sync + 'static {
    /// Amplitude storage, one entry per independent order parameter.
    type Amplitudes: Clone + Copy + Send + Sync + Default + core::fmt::Debug;

    /// Number of independent amplitudes. Equal to the dimension of the
    /// invariant space modulo `SO(3)`.
    const N_AMPLITUDES: usize;

    /// Lowest `m` whose invariant subspace of `Sym^m(R^3)` separates cosets.
    const INVARIANT_RANK: usize;

    /// Group order, or `None` for the two continuous families.
    const ORDER: Option<usize>;

    /// Every element of `H^`, for Reynolds averaging. Empty for the
    /// continuous families, whose averaging is handled analytically.
    fn elements() -> impl Iterator<Item = Rotor3>;

    /// Whether a rotor lies in `H^`, to `tol` in each component.
    fn contains(r: &Rotor3, tol: f64) -> bool;

    /// The canonical representative of the coset `r H^`.
    fn canonical(r: Rotor3) -> Rotor3;

    /// Runtime tag.
    fn kind() -> PointGroupKind;
}

/// Squared Euclidean distance between two rotors in `R^4`.
fn dist_sq(a: &Rotor3, b: &Rotor3) -> f64 {
    let (dw, dx, dy, dz) = (a.w - b.w, a.x - b.x, a.y - b.y, a.z - b.z);
    dw * dw + dx * dx + dy * dy + dz * dz
}

/// The canonical representative of `r H^`: the element of the orbit closest to
/// the identity, with ties broken by lexicographic order on the components so
/// the choice is deterministic.
fn canonical_by_orbit<H: SymmetryGroup>(r: Rotor3) -> Rotor3 {
    let mut best = r;
    let mut best_d = dist_sq(&r, &Rotor3::IDENTITY);
    for h in H::elements() {
        let c = r.compose(&h);
        let d = dist_sq(&c, &Rotor3::IDENTITY);
        if d < best_d - 1e-12
            || (d < best_d + 1e-12
                && (c.w, c.x, c.y, c.z) < (best.w, best.x, best.y, best.z))
        {
            best = c;
            best_d = d;
        }
    }
    best
}

/// Whether `r` matches any element of the enumerated group.
fn contains_by_orbit<H: SymmetryGroup>(r: &Rotor3, tol: f64) -> bool {
    H::elements().any(|h| dist_sq(r, &h) < tol * tol)
}

// --- Dicyclic (binary dihedral) ---------------------------------------------

/// The dicyclic group of order `4K`, the binary lift of the dihedral group
/// `D_K`. `Dicyclic<2>` is the quaternion group `Q_8`, the biaxial case.
///
/// Generated by `a = cos(pi/K) + sin(pi/K) e23` of order `2K`, and `b = e31`.
/// The elements are `a^m` and `a^m b` for `m` in `0..2K`.
#[derive(Clone, Copy, Debug, Default)]
pub struct Dicyclic<const K: usize>;

impl<const K: usize> SymmetryGroup for Dicyclic<K> {
    type Amplitudes = [f64; 2];
    const N_AMPLITUDES: usize = 2;
    const INVARIANT_RANK: usize = K;
    const ORDER: Option<usize> = Some(4 * K);

    fn elements() -> impl Iterator<Item = Rotor3> {
        let n = 2 * K;
        (0..n).flat_map(move |m| {
            let theta = core::f64::consts::PI * (m as f64) / (K as f64);
            let (s, c) = theta.sin_cos();
            let a = Rotor3 { w: c, x: s, y: 0.0, z: 0.0 };
            let b = Rotor3 { w: 0.0, x: 0.0, y: 1.0, z: 0.0 };
            [a, a.compose(&b)]
        })
    }

    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::Dicyclic(K)
    }
}

// --- Continuous axial families ----------------------------------------------

/// Apolar axis, `D_inf_h`: the ordinary uniaxial nematic. Order-parameter
/// manifold `RP^2`, `pi_1 = Z_2`, `pi_2 = Z`.
///
/// The stabiliser is continuous, so the rotor has one gauge direction the
/// energy cannot see. That direction is exactly what `Q` has already
/// quotiented, which is why this variant reduces to a five-component tensor.
#[derive(Clone, Copy, Debug, Default)]
pub struct AxialApolar;

impl SymmetryGroup for AxialApolar {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 2;
    const ORDER: Option<usize> = None;

    fn elements() -> impl Iterator<Item = Rotor3> {
        core::iter::empty()
    }

    fn contains(_r: &Rotor3, _tol: f64) -> bool {
        true
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        r
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::AxialApolar
    }
}

/// Polar axis, `C_inf_v`. Order-parameter manifold `S^2`, `pi_1 = 0`,
/// `pi_2 = Z`.
#[derive(Clone, Copy, Debug, Default)]
pub struct AxialPolar;

impl SymmetryGroup for AxialPolar {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 1;
    const ORDER: Option<usize> = None;

    fn elements() -> impl Iterator<Item = Rotor3> {
        core::iter::empty()
    }

    fn contains(_r: &Rotor3, _tol: f64) -> bool {
        true
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        r
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::AxialPolar
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn amplitude_counts_match_the_symmetry() {
        assert_eq!(AxialApolar::N_AMPLITUDES, 1);
        assert_eq!(AxialPolar::N_AMPLITUDES, 1);
        assert_eq!(<Dicyclic<2> as SymmetryGroup>::N_AMPLITUDES, 2);
    }

    #[test]
    fn dicyclic_order_is_four_k() {
        assert_eq!(<Dicyclic<2> as SymmetryGroup>::ORDER, Some(8));
        assert_eq!(<Dicyclic<3> as SymmetryGroup>::ORDER, Some(12));
        assert_eq!(Dicyclic::<2>::elements().count(), 8);
        assert_eq!(Dicyclic::<3>::elements().count(), 12);
    }
}
