//! Symmetry groups as compile-time types.
//!
//! `Fiber` fixes `Element` and `FIBER_DIM` at compile time, so the amplitude
//! count has to be a type-level quantity. Each symmetry is therefore a unit
//! struct implementing [`SymmetryGroup`], in the same shape as `U1Spin2` and
//! `NematicFiber3D` implement `Fiber`.
//!
//! The types name the lift `H^` inside `SU(2)` directly, not the point group
//! `H` inside `SO(3)`. The projection is two-to-one exactly when `-1` lies in
//! `H^`, so a caller wanting the lift of `C_k` asks for `Cyclic<{2 * k}>`.

use cartan_core::rotor::Rotor3;

/// Runtime tag for a symmetry, for serialisation and error messages.
///
/// Dispatch is static through [`SymmetryGroup`]; this is the value-level
/// counterpart.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PointGroupKind {
    /// Cyclic of order `n` inside `SU(2)`.
    Cyclic(usize),
    /// Dicyclic (binary dihedral) of order `4k`.
    Dicyclic(usize),
    /// Binary tetrahedral, order 24.
    BinaryTetrahedral,
    /// Binary octahedral, order 48.
    BinaryOctahedral,
    /// Binary icosahedral, order 120.
    BinaryIcosahedral,
    /// Continuous polar axis, `C_inf_v`; order-parameter manifold `S^2`.
    AxialPolar,
    /// Continuous apolar axis, `D_inf_h`; order-parameter manifold `RP^2`.
    AxialApolar,
}

/// A molecular symmetry, as the subgroup `H^` of `SU(2)` that stabilises the
/// order parameter.
///
/// Not object safe: `elements` returns `impl Iterator`, and dispatch here is
/// static by design. Use [`PointGroupKind`] where a runtime value is wanted.
pub trait SymmetryGroup: Clone + Copy + Send + Sync + 'static {
    /// Amplitude storage, one entry per independent order parameter.
    type Amplitudes: Clone + Copy + Send + Sync + Default + core::fmt::Debug;

    /// Number of independent amplitudes. Equal to the dimension of the
    /// invariant space modulo `SO(3)`.
    const N_AMPLITUDES: usize;

    /// Lowest `m` whose invariant subspace of `Sym^m(R^3)` separates cosets.
    const INVARIANT_RANK: usize;

    /// Group order, or `None` for the two continuous families.
    const ORDER: Option<usize>;

    /// Every element of `H^`, for Reynolds averaging. Empty for the
    /// continuous families, whose averaging is handled analytically.
    fn elements() -> impl Iterator<Item = Rotor3>;

    /// Whether a rotor lies in `H^`, to `tol` in each component.
    fn contains(r: &Rotor3, tol: f64) -> bool;

    /// The canonical representative of the coset `r H^`.
    fn canonical(r: Rotor3) -> Rotor3;

    /// Runtime tag.
    fn kind() -> PointGroupKind;
}

/// Squared Euclidean distance between two rotors in `R^4`.
fn dist_sq(a: &Rotor3, b: &Rotor3) -> f64 {
    let (dw, dx, dy, dz) = (a.w - b.w, a.x - b.x, a.y - b.y, a.z - b.z);
    dw * dw + dx * dx + dy * dy + dz * dz
}

/// The canonical representative of `r H^`: the element of the orbit closest to
/// the identity, with ties broken by lexicographic order on the components so
/// the choice is deterministic.
fn canonical_by_orbit<H: SymmetryGroup>(r: Rotor3) -> Rotor3 {
    let mut best = r;
    let mut best_d = dist_sq(&r, &Rotor3::IDENTITY);
    for h in H::elements() {
        let c = r.compose(&h);
        let d = dist_sq(&c, &Rotor3::IDENTITY);
        if d < best_d - 1e-12
            || (d < best_d + 1e-12 && (c.w, c.x, c.y, c.z) < (best.w, best.x, best.y, best.z))
        {
            best = c;
            best_d = d;
        }
    }
    best
}

/// Whether `r` matches any element of the enumerated group.
fn contains_by_orbit<H: SymmetryGroup>(r: &Rotor3, tol: f64) -> bool {
    H::elements().any(|h| dist_sq(r, &h) < tol * tol)
}

// --- Dicyclic (binary dihedral) ---------------------------------------------

/// The dicyclic group of order `4K`, the binary lift of the dihedral group
/// `D_K`. `Dicyclic<2>` is the quaternion group `Q_8`, the biaxial case.
///
/// Generated by `a = cos(pi/K) + sin(pi/K) e23` of order `2K`, and `b = e31`.
/// The elements are `a^m` and `a^m b` for `m` in `0..2K`.
#[derive(Clone, Copy, Debug, Default)]
pub struct Dicyclic<const K: usize>;

impl<const K: usize> SymmetryGroup for Dicyclic<K> {
    type Amplitudes = [f64; 2];
    const N_AMPLITUDES: usize = 2;
    const INVARIANT_RANK: usize = K;
    const ORDER: Option<usize> = Some(4 * K);

    fn elements() -> impl Iterator<Item = Rotor3> {
        let n = 2 * K;
        (0..n).flat_map(move |m| {
            let theta = core::f64::consts::PI * (m as f64) / (K as f64);
            let (s, c) = theta.sin_cos();
            let a = Rotor3 {
                w: c,
                x: s,
                y: 0.0,
                z: 0.0,
            };
            let b = Rotor3 {
                w: 0.0,
                x: 0.0,
                y: 1.0,
                z: 0.0,
            };
            [a, a.compose(&b)]
        })
    }

    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::Dicyclic(K)
    }
}

// --- Continuous axial families ----------------------------------------------

/// Apolar axis, `D_inf_h`: the ordinary uniaxial nematic. Order-parameter
/// manifold `RP^2`, `pi_1 = Z_2`, `pi_2 = Z`.
///
/// The stabiliser is continuous, so the rotor has one gauge direction the
/// energy cannot see. That direction is exactly what `Q` has already
/// quotiented, which is why this variant reduces to a five-component tensor.
#[derive(Clone, Copy, Debug, Default)]
pub struct AxialApolar;

impl SymmetryGroup for AxialApolar {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 2;
    const ORDER: Option<usize> = None;

    fn elements() -> impl Iterator<Item = Rotor3> {
        core::iter::empty()
    }

    fn contains(_r: &Rotor3, _tol: f64) -> bool {
        true
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        r
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::AxialApolar
    }
}

/// Polar axis, `C_inf_v`. Order-parameter manifold `S^2`, `pi_1 = 0`,
/// `pi_2 = Z`.
#[derive(Clone, Copy, Debug, Default)]
pub struct AxialPolar;

impl SymmetryGroup for AxialPolar {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 1;
    const ORDER: Option<usize> = None;

    fn elements() -> impl Iterator<Item = Rotor3> {
        core::iter::empty()
    }

    fn contains(_r: &Rotor3, _tol: f64) -> bool {
        true
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        r
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::AxialPolar
    }
}

/// The subgroup generated by `gens`, closed under multiplication.
///
/// Returns `None` when the closure exceeds `cap`, which means the generators do
/// not generate a finite group. Public so a caller adding a `SymmetryGroup`
/// implementation can build its element list from generators and check the
/// order rather than typing a table.
#[must_use]
pub fn closure(gens: &[Rotor3], tol: f64, cap: usize) -> Option<Vec<Rotor3>> {
    let mut out: Vec<Rotor3> = vec![Rotor3::IDENTITY];
    let mut frontier: Vec<Rotor3> = vec![Rotor3::IDENTITY];
    while !frontier.is_empty() {
        let mut next = Vec::new();
        for f in &frontier {
            for g in gens {
                let c = f.compose(g);
                if !out.iter().any(|o| dist_sq(o, &c) < tol * tol) {
                    out.push(c);
                    next.push(c);
                    if out.len() > cap {
                        return None;
                    }
                }
            }
        }
        frontier = next;
    }
    Some(out)
}

/// The 24 unit Hurwitz quaternions: the binary tetrahedral group.
fn binary_tetrahedral_elements() -> Vec<Rotor3> {
    let mut v = Vec::with_capacity(24);
    for i in 0..4 {
        for sign in [1.0_f64, -1.0] {
            let mut c = [0.0; 4];
            c[i] = sign;
            v.push(Rotor3 {
                w: c[0],
                x: c[1],
                y: c[2],
                z: c[3],
            });
        }
    }
    for m in 0..16u8 {
        let s = |b: u8| if m >> b & 1 == 0 { 0.5 } else { -0.5 };
        v.push(Rotor3 {
            w: s(0),
            x: s(1),
            y: s(2),
            z: s(3),
        });
    }
    v
}

/// The 48 elements of the binary octahedral group: the Hurwitz units plus the
/// 24 quaternions `(+/- e_a +/- e_b) / sqrt(2)` for `a < b`.
fn binary_octahedral_elements() -> Vec<Rotor3> {
    let mut v = binary_tetrahedral_elements();
    let r = core::f64::consts::FRAC_1_SQRT_2;
    for a in 0..4 {
        for b in (a + 1)..4 {
            for sa in [r, -r] {
                for sb in [r, -r] {
                    let mut c = [0.0; 4];
                    c[a] = sa;
                    c[b] = sb;
                    v.push(Rotor3 {
                        w: c[0],
                        x: c[1],
                        y: c[2],
                        z: c[3],
                    });
                }
            }
        }
    }
    v
}

/// The 120 icosians: the 24 Hurwitz units plus the 96 even permutations of
/// `(0, +/-1, +/-1/phi, +/-phi) / 2`.
fn binary_icosahedral_elements() -> Vec<Rotor3> {
    let mut v = binary_tetrahedral_elements();
    let phi = (1.0 + 5.0_f64.sqrt()) / 2.0;
    let base = [0.0, 0.5, 0.5 / phi, 0.5 * phi];
    // The 12 even permutations of four symbols.
    const EVEN: [[usize; 4]; 12] = [
        [0, 1, 2, 3],
        [0, 2, 3, 1],
        [0, 3, 1, 2],
        [1, 0, 3, 2],
        [1, 2, 0, 3],
        [1, 3, 2, 0],
        [2, 0, 1, 3],
        [2, 1, 3, 0],
        [2, 3, 0, 1],
        [3, 0, 2, 1],
        [3, 1, 0, 2],
        [3, 2, 1, 0],
    ];
    for p in EVEN {
        for m in 0..8u8 {
            let mut c = [0.0; 4];
            let mut bit = 0;
            for slot in 0..4 {
                let val = base[p[slot]];
                if val == 0.0 {
                    c[slot] = 0.0;
                } else {
                    c[slot] = if m >> bit & 1 == 0 { val } else { -val };
                    bit += 1;
                }
            }
            v.push(Rotor3 {
                w: c[0],
                x: c[1],
                y: c[2],
                z: c[3],
            });
        }
    }
    v
}

/// A precomputed group table.
///
/// `elements()` recomputes on every call by design: a `static` cache inside a
/// generic function is shared across every monomorphisation in Rust, so a
/// cache keyed that way would hand `Dicyclic<3>` the elements of `Dicyclic<2>`.
/// Hot paths build one of these instead and hold it.
#[derive(Clone, Debug)]
pub struct GroupTable<H: SymmetryGroup> {
    elements: Vec<Rotor3>,
    _marker: core::marker::PhantomData<H>,
}

impl<H: SymmetryGroup> GroupTable<H> {
    /// Enumerate the group once.
    #[must_use]
    pub fn new() -> Self {
        Self {
            elements: H::elements().collect(),
            _marker: core::marker::PhantomData,
        }
    }

    /// The enumerated elements.
    #[must_use]
    pub fn elements(&self) -> &[Rotor3] {
        &self.elements
    }
}

impl<H: SymmetryGroup> Default for GroupTable<H> {
    fn default() -> Self {
        Self::new()
    }
}

// --- Cyclic ------------------------------------------------------------------

/// The cyclic group of order `N` inside `SU(2)`, generated by
/// `cos(2 pi / N) + sin(2 pi / N) e23`.
///
/// Contains `-1` only when `N` is even, so `Cyclic<N>` with odd `N` maps
/// isomorphically onto a rotation group and is not a binary lift.
#[derive(Clone, Copy, Debug, Default)]
pub struct Cyclic<const N: usize>;

impl<const N: usize> SymmetryGroup for Cyclic<N> {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = N;
    const ORDER: Option<usize> = Some(N);

    fn elements() -> impl Iterator<Item = Rotor3> {
        (0..N).map(move |m| {
            let theta = 2.0 * core::f64::consts::PI * (m as f64) / (N as f64);
            let (s, c) = theta.sin_cos();
            Rotor3 {
                w: c,
                x: s,
                y: 0.0,
                z: 0.0,
            }
        })
    }

    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }

    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }

    fn kind() -> PointGroupKind {
        PointGroupKind::Cyclic(N)
    }
}

// --- Polyhedral --------------------------------------------------------------

/// The binary tetrahedral group, order 24.
#[derive(Clone, Copy, Debug, Default)]
pub struct BinaryTetrahedral;

impl SymmetryGroup for BinaryTetrahedral {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 3;
    const ORDER: Option<usize> = Some(24);

    fn elements() -> impl Iterator<Item = Rotor3> {
        binary_tetrahedral_elements().into_iter()
    }
    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }
    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }
    fn kind() -> PointGroupKind {
        PointGroupKind::BinaryTetrahedral
    }
}

/// The binary octahedral group, order 48. The cubatic symmetry.
#[derive(Clone, Copy, Debug, Default)]
pub struct BinaryOctahedral;

impl SymmetryGroup for BinaryOctahedral {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 4;
    const ORDER: Option<usize> = Some(48);

    fn elements() -> impl Iterator<Item = Rotor3> {
        binary_octahedral_elements().into_iter()
    }
    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }
    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }
    fn kind() -> PointGroupKind {
        PointGroupKind::BinaryOctahedral
    }
}

/// The binary icosahedral group, order 120.
#[derive(Clone, Copy, Debug, Default)]
pub struct BinaryIcosahedral;

impl SymmetryGroup for BinaryIcosahedral {
    type Amplitudes = [f64; 1];
    const N_AMPLITUDES: usize = 1;
    const INVARIANT_RANK: usize = 6;
    const ORDER: Option<usize> = Some(120);

    fn elements() -> impl Iterator<Item = Rotor3> {
        binary_icosahedral_elements().into_iter()
    }
    fn contains(r: &Rotor3, tol: f64) -> bool {
        contains_by_orbit::<Self>(r, tol)
    }
    fn canonical(r: Rotor3) -> Rotor3 {
        canonical_by_orbit::<Self>(r)
    }
    fn kind() -> PointGroupKind {
        PointGroupKind::BinaryIcosahedral
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn amplitude_counts_match_the_symmetry() {
        assert_eq!(AxialApolar::N_AMPLITUDES, 1);
        assert_eq!(AxialPolar::N_AMPLITUDES, 1);
        assert_eq!(<Dicyclic<2> as SymmetryGroup>::N_AMPLITUDES, 2);
    }

    #[test]
    fn dicyclic_order_is_four_k() {
        assert_eq!(<Dicyclic<2> as SymmetryGroup>::ORDER, Some(8));
        assert_eq!(<Dicyclic<3> as SymmetryGroup>::ORDER, Some(12));
        assert_eq!(Dicyclic::<2>::elements().count(), 8);
        assert_eq!(Dicyclic::<3>::elements().count(), 12);
    }

    const TOL: f64 = 1e-10;

    fn near(a: &Rotor3, b: &Rotor3) -> bool {
        dist_sq(a, b) < TOL * TOL
    }

    /// Order, distinctness, unit norm, closure, and inverses, for any finite
    /// group. A construction that is not a group fails at least one of these.
    fn check_group_axioms<H: SymmetryGroup>(name: &str) {
        let g: Vec<Rotor3> = H::elements().collect();
        let order = H::ORDER.unwrap_or_else(|| panic!("{name} has no order"));
        assert_eq!(g.len(), order, "{name}: element count");

        for (i, a) in g.iter().enumerate() {
            let n = (a.w * a.w + a.x * a.x + a.y * a.y + a.z * a.z).sqrt();
            assert!((n - 1.0).abs() < 1e-12, "{name}: element {i} has norm {n}");
            for (j, b) in g.iter().enumerate() {
                assert!(
                    i == j || !near(a, b),
                    "{name}: elements {i} and {j} coincide"
                );
            }
        }

        assert!(
            g.iter().any(|e| near(e, &Rotor3::IDENTITY)),
            "{name}: identity missing"
        );

        for (i, a) in g.iter().enumerate() {
            for (j, b) in g.iter().enumerate() {
                let c = a.compose(b);
                assert!(
                    g.iter().any(|e| near(e, &c)),
                    "{name}: product of {i} and {j} left the group"
                );
            }
            let inv = a.reverse();
            assert!(
                g.iter().any(|e| near(e, &inv)),
                "{name}: element {i} has no inverse in the group"
            );
        }
    }

    #[test]
    fn cyclic_is_a_group() {
        check_group_axioms::<Cyclic<1>>("Cyclic<1>");
        check_group_axioms::<Cyclic<2>>("Cyclic<2>");
        check_group_axioms::<Cyclic<3>>("Cyclic<3>");
        check_group_axioms::<Cyclic<6>>("Cyclic<6>");
    }

    #[test]
    fn dicyclic_is_a_group() {
        check_group_axioms::<Dicyclic<1>>("Dicyclic<1>");
        check_group_axioms::<Dicyclic<2>>("Dicyclic<2>");
        check_group_axioms::<Dicyclic<3>>("Dicyclic<3>");
        check_group_axioms::<Dicyclic<5>>("Dicyclic<5>");
    }

    #[test]
    fn polyhedral_are_groups() {
        check_group_axioms::<BinaryTetrahedral>("2T");
        check_group_axioms::<BinaryOctahedral>("2O");
        check_group_axioms::<BinaryIcosahedral>("2I");
    }

    #[test]
    fn minus_one_is_present_exactly_when_expected() {
        let minus = Rotor3 {
            w: -1.0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
        };
        let has = |v: Vec<Rotor3>| v.iter().any(|e| near(e, &minus));
        assert!(
            !has(Cyclic::<3>::elements().collect()),
            "odd cyclic must omit -1"
        );
        assert!(
            has(Cyclic::<4>::elements().collect()),
            "even cyclic must contain -1"
        );
        assert!(has(Dicyclic::<2>::elements().collect()));
        assert!(has(BinaryTetrahedral::elements().collect()));
        assert!(has(BinaryOctahedral::elements().collect()));
        assert!(has(BinaryIcosahedral::elements().collect()));
    }

    #[test]
    fn explicit_lists_agree_with_generated_closure() {
        // 2T is generated by i and (1+i+j+k)/2; 2O by 2T's generators plus
        // (1+i)/sqrt(2); 2I is checked by closing on two of its own elements.
        let h = 0.5;
        let i = Rotor3 {
            w: 0.0,
            x: 1.0,
            y: 0.0,
            z: 0.0,
        };
        let omega = Rotor3 {
            w: h,
            x: h,
            y: h,
            z: h,
        };
        let t = closure(&[i, omega], TOL, 200).expect("2T closure is finite");
        assert_eq!(t.len(), 24, "2T generated order");

        let r = core::f64::consts::FRAC_1_SQRT_2;
        let s = Rotor3 {
            w: r,
            x: r,
            y: 0.0,
            z: 0.0,
        };
        let o = closure(&[i, omega, s], TOL, 400).expect("2O closure is finite");
        assert_eq!(o.len(), 48, "2O generated order");

        for e in binary_tetrahedral_elements() {
            assert!(t.iter().any(|g| near(g, &e)), "2T list is not the closure");
        }
        for e in binary_octahedral_elements() {
            assert!(o.iter().any(|g| near(g, &e)), "2O list is not the closure");
        }
    }

    #[test]
    fn contains_and_canonical_behave() {
        for e in Dicyclic::<3>::elements() {
            assert!(Dicyclic::<3>::contains(&e, TOL));
        }
        let off = Rotor3 {
            w: 0.3,
            x: 0.4,
            y: 0.5,
            z: core::f64::consts::FRAC_1_SQRT_2,
        };
        assert!(!Dicyclic::<3>::contains(&off, TOL));

        let r = Rotor3 {
            w: 0.6,
            x: 0.8,
            y: 0.0,
            z: 0.0,
        };
        let c = Dicyclic::<3>::canonical(r);
        assert!(
            near(&c, &Dicyclic::<3>::canonical(c)),
            "canonical is not idempotent"
        );
        for h in Dicyclic::<3>::elements() {
            let moved = r.compose(&h);
            assert!(
                near(&Dicyclic::<3>::canonical(moved), &c),
                "canonical is not constant on the orbit"
            );
        }
    }

    #[test]
    fn group_table_matches_the_iterator() {
        let table = GroupTable::<Dicyclic<3>>::new();
        let direct: Vec<Rotor3> = Dicyclic::<3>::elements().collect();
        assert_eq!(table.elements().len(), direct.len());
        for (a, b) in table.elements().iter().zip(direct.iter()) {
            assert!(near(a, b));
        }
    }
}
